[package]
name = "solvio"
version = "0.1.0"
authors = ["Andrey Vasnetsov <vasnetsov93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tempdir = "0.3.7"
criterion = "0.3"


[dependencies]

thiserror = "1.0"
log = "0.4"
env_logger = "0.7.1"
rand = "0.7.3"
wal = { git = "https://github.com/generall/wal.git" }
serde = { version = "~1.0", features = ["derive"] }
serde_yaml = "~0.8"
serde_json = "~1.0"
serde_cbor = "0.11.1"

config = "~0.10.1"

actix-web = "2.0"
actix-rt = "1.0"

[[bin]]
name = "service"
path = "src/service.rs"
test = false
bench = false


[[bench]]
name = "dyn_benchmark"
harness = false
