[package]
name = "solvio"
version = "0.4.2"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]
edition = "2021"
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "web" ]
web = ["actix-web"]
grpc = ["tonic", "tonic-build", "prost", "num-traits"]
service_debug = ["parking_lot", "parking_lot/deadlock_detection"]


[dev-dependencies]
tempdir = "0.3.7"


[dependencies]

parking_lot = { version = "0.12", features=["deadlock_detection"], optional = true }

num_cpus = "1.13"
thiserror = "1.0"
log = "0.4"
env_logger = "0.9.0"
rand = "0.8.4"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
schemars = { version = "0.8.8", features = ["uuid"] }
itertools = "0.10"

config = "~0.11.0"

tokio = { version = "~1.16", features = ["full"] }

actix-web = { version = "4.0.0-rc.1", optional = true }
tonic =  { version = "0.6.2", optional = true }
num-traits = { version = "0.2.14", optional = true }
prost = { version = "0.9", optional = true }

segment = { path = "lib/segment" }
collection = { path = "lib/collection" }
storage = { path = "lib/storage" }

[build-dependencies]
tonic-build = { version = "0.6.2", features = ["prost"], optional = true }

[patch.crates-io]
# Env flag OPENBLAS_DYNAMIC_ARCH is implemented in this custom fork
# Which allows to build openblas with dynamic CPU architecture selection
openblas-src = { git = "https://github.com/solvio/openblas-src.git" }

[[bin]]
name = "schema_generator"
path = "src/schema_generator.rs"
test = false
bench = false

[[bin]]
name = "cli"
path = "src/cli.rs"
test = false
bench = false

[workspace]
members = ["lib/*"]
