[package]
name = "solvio"
version = "0.1.0"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]
edition = "2018"
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tempdir = "0.3.7"
criterion = "0.3"


[dependencies]

num_cpus = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.7.1"
rand = "0.7.3"
wal = { git = "https://github.com/generall/wal.git" }
tokio = {version = "0.2.21", features = ["rt-threaded"]}
serde = { version = "~1.0", features = ["derive"] }
serde_yaml = "~0.8"
serde_json = "~1.0"
serde_cbor = "0.11.1"

config = "~0.10.1"

actix-web = "2.0"
actix-rt = "1.0"

sled = "0.34"

segment = {path = "lib/segment"}
collection = {path = "lib/collection"}
storage = {path = "lib/storage"}



[workspace]
members = ["lib/*"]

[[bin]]
name = "service"
path = "src/service.rs"
test = false
bench = false
build = false


[[bench]]
name = "dyn_benchmark"
harness = false
