[package]
name = "solvio"
version = "0.1.0"
authors = ["Andrey Vasnetsov <vasnetsov93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.7.3"
wal = { git = "https://github.com/generall/wal.git" }
serde = { version = "~1.0", features = ["derive"] }
serde_yaml = "~0.8"
bincode = "~1.2.1"

config = "~0.10.1"
