[package]
name = "solvio"
version = "0.6.0"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]
edition = "2021"
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "web" ]
web = ["actix-web"]
service_debug = ["parking_lot", "parking_lot/deadlock_detection"]
consensus = ["raft", "slog", "slog-stdlog", "storage/consensus"]


[dev-dependencies]
tempdir = "0.3.7"
rusty-hook = "^0.11.2"


[dependencies]

parking_lot = { version = "0.12", features=["deadlock_detection"], optional = true }

num_cpus = "1.13"
thiserror = "1.0"
log = "0.4"
env_logger = "0.9.0"
rand = "0.8.5"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
schemars = { version = "0.8.8", features = ["uuid"] }
itertools = "0.10"
uuid = { version = "0.8", features = ["v4", "serde"] }

config = "~0.12.0"

tokio = { version = "~1.17", features = ["full"] }

actix-web = { version = "4.0.1", optional = true }
tonic = "0.6.2"
num-traits = "0.2.14"
prost = "0.9"
prost-types = "0.9.0"

raft = { version = "0.6.0", features = ["prost-codec"], default-features = false, optional = true }
slog =  { version = "2.7.0", optional = true }
slog-stdlog = { version = "4.1.1", optional = true }

segment = { path = "lib/segment" }
collection = { path = "lib/collection" }
storage = { path = "lib/storage" }

[build-dependencies]
tonic-build = { version = "0.6.2", features = ["prost"] }

[[bin]]
name = "schema_generator"
path = "src/schema_generator.rs"
test = false
bench = false

[workspace]
members = ["lib/*"]
