[package]
name = "solvio"
version = "0.7.0"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]
edition = "2021"
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "web" ]
web = ["actix-web"]
service_debug = ["parking_lot", "parking_lot/deadlock_detection"]

[dev-dependencies]
tempdir = "0.3.7"
rusty-hook = "^0.11.2"


[dependencies]

parking_lot = { version = "0.12", features=["deadlock_detection"], optional = true }

num_cpus = "1.13"
thiserror = "1.0"
log = "0.4"
env_logger = "0.9.0"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
schemars = { version = "0.8.8", features = ["uuid"] }
itertools = "0.10"
anyhow = "1.0.57"
futures = "0.3.21"
clap = { version = "3.1.18", features = ["derive"] }
serde_cbor = { version = "0.11.2"}

config = "~0.13.1"

tokio = { version = "~1.18", features = ["full"] }

actix-web = { version = "4.0.1", optional = true }
tonic = "0.7.2"
num-traits = "0.2.15"

# Consensus related crates
raft = { version = "=0.6.0", features = ["prost-codec"], default-features = false }
slog = "2.7.0"
slog-stdlog = "4.1.1"
prost = "=0.7.0"
raft-proto = { version = "=0.6.0", features = ["prost-codec"], default-features = false}

segment = { path = "lib/segment" }
collection = { path = "lib/collection" }
storage = { path = "lib/storage" }
api = { path = "lib/api" }

[[bin]]
name = "schema_generator"
path = "src/schema_generator.rs"
test = false
bench = false

[workspace]
members = ["lib/*"]
