[package]
name = "solvio"
version = "0.8.4"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]
edition = "2021"
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [ "web", "parking_lot" ]
web = ["actix-web"]
service_debug = ["parking_lot", "parking_lot/deadlock_detection"]

[dev-dependencies]
tempdir = "0.3.7"
rusty-hook = "^0.11.2"


[dependencies]

parking_lot = { version = "0.12.1", features=["deadlock_detection"], optional = true }

num_cpus = "1.13"
thiserror = "1.0"
log = "0.4"
env_logger = "0.9.0"
atty = "0.2"
colored = "2"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
chrono = { version = "~0.4", features = ["serde"] }
schemars = { version = "0.8.10", features = ["uuid1", "preserve_order", "chrono"] }
itertools = "0.10"
anyhow = "1.0.58"
futures = "0.3.21"
futures-util = "0.3.21"
clap = { version = "3.2.14", features = ["derive"] }
serde_cbor = { version = "0.11.2"}
uuid = { version = "1.1", features = ["v4", "serde"] }
sys-info = "0.9.1"

config = "~0.13.1"

tokio = { version = "~1.20", features = ["full"] }

actix-web = { version = "4.1.0", optional = true }
actix-cors = "0.6.1"
actix-files = "0.6.1"
tonic = "0.7.2"
num-traits = "0.2.15"
tar = "0.4.38"

# Consensus related crates
raft = { git = "https://github.com/tikv/raft-rs", rev = "52d84aac8734369d81c2d77413ea3ab8e58e0af9", features = ["prost-codec"], default-features = false }
slog = "2.7.0"
slog-stdlog = "4.1.1"
prost = "=0.9.0"
raft-proto = {  git = "https://github.com/tikv/raft-rs", rev = "52d84aac8734369d81c2d77413ea3ab8e58e0af9", features = ["prost-codec"], default-features = false}

segment = { path = "lib/segment" }
collection = { path = "lib/collection" }
storage = { path = "lib/storage" }
api = { path = "lib/api" }

[[bin]]
name = "schema_generator"
path = "src/schema_generator.rs"
test = false
bench = false

[workspace]
members = ["lib/*"]
