[package]
name = "solvio"
version = "0.11.1"
authors = [
    "Andrey Vasnetsov <andrey@vasnetsov.com>",
    "Solvio Team <info@solvio.tech>",
]
readme = "README.md"
homepage = "https://solvio.tech/"
repository = "https://github.com/solvio/solvio"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.75"
default-run = "solvio"

[features]
default = ["web", "parking_lot"]
web = ["actix-web"]
multiling-chinese = ["segment/multiling-chinese"]
multiling-japanese = ["segment/multiling-japanese"]
multiling-korean = ["segment/multiling-korean"]
service_debug = ["parking_lot", "parking_lot/deadlock_detection"]
tracing = [
    "api/tracing",
    "collection/tracing",
    "segment/tracing",
    "storage/tracing",
]
console = ["console-subscriber"]
console-subscriber = ["tracing", "dep:console-subscriber"]
tracy = ["tracing-tracy"]
tracing-tracy = ["tracing", "dep:tracing-tracy"]
tokio-tracing = ["tokio/tracing"]
stacktrace = ["rstack-self"]

[dev-dependencies]
serde_urlencoded = "0.7"
sealed_test = "1.0.0"

tempfile = "3.10.1"
rusty-hook = "^0.11.2"


[dependencies]
parking_lot = { workspace = true, optional = true }

thiserror = "1.0"
log = "0.4"
colored = "2"
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { version = "~0.4", features = ["serde"] }
rand = "0.8.5"
schemars = { workspace = true }
itertools = "0.12"
anyhow = "1.0.80"
futures = { workspace = true }
futures-util = { workspace = true }
clap = { version = "4.5.1", features = ["derive"] }
serde_cbor = { workspace = true }
uuid = { workspace = true }
sys-info = "0.9.1"
wal = { git = "https://github.com/solvio/wal.git", rev = "fad0e7c48be58d8e7db4cc739acd9b1cf6735de0" }

config = "~0.14.0"

tokio = { workspace = true }

actix-cors = "0.7.0"
actix-files = "0.6.5"
actix-web = { version = "4.5.1", optional = true, features = ["rustls-0_22", "actix-tls"] }
actix-web-httpauth = "0.8.1"
actix-web-validator = "5.0.1"
tonic = { workspace = true }
tonic-reflection = { workspace = true }
tower = { version = "0.4.13", features = ["filter"] }
tower-layer = "0.3.2"
tar = "0.4.40"
reqwest = { version = "0.11", default-features = false, features = ["stream", "rustls-tls", "blocking"] }
rustls = "0.22.2"
rustls-pki-types = "1.3.1"
rustls-pemfile = "2.1.1"
prometheus = { version = "0.13.3", default-features = false }
validator = { version = "0.16", features = ["derive"] }

# Consensus related crates
raft = { version = "0.7.0", features = ["prost-codec"], default-features = false }
slog = { version = "2.7.0", features = ["max_level_trace", "release_max_level_debug"] }
slog-stdlog = "4.1.1"
prost = { workspace = true }
raft-proto = { version = "0.7.0", features = ["prost-codec"], default-features = false }

common = { path = "lib/common/common" }
cancel = { path = "lib/common/cancel" }
memory = { path = "lib/common/memory" }
issues = { path = "lib/common/issues" }
segment = { path = "lib/segment" }
collection = { path = "lib/collection" }
storage = { path = "lib/storage" }
api = { path = "lib/api" }
actix-multipart = "0.6.1"
constant_time_eq = "0.3.0"

# Profiling
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = { version = "0.2", default-features = false, features = ["log-tracer", "std"] }
console-subscriber = { version = "0.1", default-features = false, features = ["parking_lot"], optional = true }
tracing-tracy = { version = "0.11.0", features = ["ondemand"], optional = true }

# Backtrace
[target.'cfg(target_os = "linux")'.dependencies]
rstack-self = { version = "0.3.0", optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[workspace.dependencies]
fnv = "1.0"
futures = "0.3.30"
futures-util = "0.3.30"
indexmap = { version = "2", features = ["serde"] }
parking_lot = { version = "0.12.1", features = ["deadlock_detection", "serde"] }
prost = "0.11.9"
prost-wkt-types = "0.4.2"
schemars = { version = "0.8.16", features = ["uuid1", "preserve_order", "chrono", "url", "indexmap2"] }
semver = { version = "1.0", features = ["serde"] }
serde = { version = "~1.0", features = ["derive", "rc"] }
serde_cbor = { version = "0.11.2" }
serde_json = "~1.0"
tokio = { version = "~1.36", features = ["full"] }
tokio-util = "0.7"
tonic = { version = "0.9.2", features = ["gzip", "tls"] }
tonic-reflection = "0.9.2"
tracing = { version = "0.1", features = ["async-await"] }
uuid = { version = "1.7", features = ["v4", "serde"] }

[[bin]]
name = "schema_generator"
path = "src/schema_generator.rs"
test = false
bench = false

[[bin]]
name = "wal_inspector"
path = "src/wal_inspector.rs"
test = false
bench = false

[workspace]
members = [
    "lib/api",
    "lib/collection",
    "lib/common/*",
    "lib/rbac",
    "lib/segment",
    "lib/sparse",
    "lib/storage",
]

[profile.release]
lto = "fat"

# Inherit from release, because we are not rebuilding often,
# and we don't want the huge binary sizes from debug builds.
[profile.ci]
inherits = "release"
lto = false
opt-level = 0

# Inherits by default from release
[profile.bench]
lto = false
debug = true

# Profile for performance testing, which is faster to build than release.
[profile.perf]
inherits = "release"
lto = false
opt-level = 3

[patch.crates-io]
# Temporary patch until <https://github.com/hyperium/tonic/pull/1401> is merged
tonic = { git = 'https://github.com/solvio/tonic', branch = "v0.9.2-patched" }
