[package]
name = "solvio"
version = "0.3.4"
authors = ["Andrey Vasnetsov <andrey@vasnetsov.com>"]
edition = "2018"
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
tempdir = "0.3.7"
criterion = "0.3"


[dependencies]

num_cpus = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.7.1"
rand = "0.7.3"
serde = { version = "~1.0", features = ["derive"] }
serde_yaml = "~0.8"
serde_json = "~1.0"
schemars = "0.8.0"
itertools = "0.9"

config = "~0.10.1"

actix-web = "4.0.0-beta.8"
tokio = { version = "~1.7", features = ["full"] }


segment = {path = "lib/segment"}
collection = {path = "lib/collection"}
storage = {path = "lib/storage"}

[[bin]]
name = "schema_generator"
path = "src/schema_generator.rs"
test = false
bench = false

[[bin]]
name = "cli"
path = "src/cli.rs"
test = false
bench = false

[workspace]
members = ["lib/*"]
