export solvio__GPU__indexing=1
export solvio__GPU__max_groups=512
export solvio__GPU__force_half_precision=0

export solvio__GPU__device_filter=LLVM

export solvio__storage__optimizers__max_optimization_threads=1

cargo run --release
