#@ load("openapi.lib.yml", "response", "reference", "type", "array")

paths:
  /telemetry:
    get:
      summary: Collect telemetry data
      description: Collect telemetry data including app info, system info, collections info, cluster info, configs and statistics
      operationId: telemetry
      tags:
        - service
      parameters:
        - name: anonymize
          in: query
          description: "If true, anonymize result"
          required: false
          schema:
            type: boolean
      responses: #@ response(array(reference("TelemetryData")))

  /locks:
    post:
      summary: Set lock options
      description: Set lock options. If write is locked, all write operations and collection creation are forbidden. Returns previous lock options
      operationId: post_locks
      tags:
        - service
      requestBody:
        description: Lock options and optional error message
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LocksOption"
      responses: #@ response(reference("LocksOption"))

    get:
      summary: Get lock options
      description: Get lock options. If write is locked, all write operations and collection creation are forbidden
      operationId: get_locks
      tags:
        - service
      responses: #@ response(reference("LocksOption"))
