storage:
  storage_path: ./storage
  wal:
    wal_capacity_mb: 32
    wal_segments_ahead: 0


  performance:
    # Number of parallel threads used for search operations. If 0 - auto selection.
    max_search_threads: 0

    # Number of parallel threads used for index optimization. If 0 - auto selection.
    max_optimize_threads: 0


  optimizers:
    # The minimal fraction of deleted vectors in a segment, required to perform segment optimization
    deleted_threshold: 0.2

    # The minimal number of vectors in a segment, required to perform segment optimization
    vacuum_min_vector_number: 1000

    # If the number of segments exceeds this value, the optimizer will merge the smallest segments.
    max_segment_number: 5

    # Maximum number of vectors to store in-memory per segment. Segments larger than this threshold will be stored as read-only memmaped file.
    memmap_threshold: 50_000

    # Maximum number of vectors allowed for plain index. Default value based on https://github.com/google-research/google-research/blob/master/scann/docs/algorithms.md
    indexing_threshold: 20_000

    # Minimum interval between forced flushes.
    flush_interval_sec: 60


service:
  host: 0.0.0.0
  port: 6333
